### ISSUE TITLE
api for collyfront ?

### ISSUE THREAD

**Issue by ghost** [hantmac/CollyFront#2]
Hi,

Hope you are all well !

Is there an api available for this front-end ?
I am working on a project for scraping with gocolly and I am interested to give a try to your front.

You should check also if you want to improve your front:
- https://github.com/dioptre/scrp (using gocolly, protobuf and cassandra)
- https://github.com/crawlab-team/crawlab (written in golang/vuejs)

Thanks for the api in advance.

Cheers,
X

**Comment by hantmac** [comment]
> Hi,
> 
> Hope you are all well !
> 
> Is there an api available for this front-end ?
> I am working on a project for scraping with gocolly and I am interested to give a try to your front.
> 
> You should check also if you want to improve your front:
> 
> * https://github.com/dioptre/scrp (using gocolly, protobuf and cassandra)
> * https://github.com/crawlab-team/crawlab (written in golang/vuejs)
> 
> Thanks for the api in advance.
> 
> Cheers,
> X

Hi X,
Thanks for your issue, and When I made web ui `colly front, I discovered the crawlab project, so I joined the crawlab and I am a member of the crawlab 😄 . We are working hard to build the crawlab, you can try to use it. If you have any issue, feel free to open.

**Comment by ghost** [comment]
I have opened one, much more feature requests :-) https://github.com/crawlab-team/crawlab/issues/652

**Comment by hantmac** [comment]
Talk on another issue, closing.
